services:
    web:
        image: nginx:latest
        expose:
            - 80
        volumes:
            - ../files/src:/var/www/html:rw
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
        networks:
            - dokploy-network

    php-fpm:
        build: docker/php-fpm
        expose:
            - 9000
        volumes:
            - ../files/src:/var/www/html:rw
        networks:
            - dokploy-network
        user: "33:33"  # 使用 www-data 的 33:33

networks:
  dokploy-network:
    external: true
