version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-local-development-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/django_db
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      - db
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8001

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
